plugins { id 'com.android.application' }

android {
    namespace 'com.ycfs.openvideosaver'
    compileSdk 35
    defaultConfig {
        applicationId 'com.ycfs.openvideosaver'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.2.0-alpha.1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildTypes {
        release { minifyEnabled false }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
